[2016-01-26 12:49:52.359] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 12:54:11.077] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 12:54:49.225] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 12:59:15.250] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:00:15.902] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:00:48.671] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:01:36.927] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:03:21.805] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:05:58.047] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:09:00.855] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:69:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:16:26.174] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:16:31.040] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:16:57.468] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:17:38.962] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:18:54.176] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:20:11.757] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:73:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:25:01.188] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:25:41.694] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:26:33.879] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:32:30.202] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:32:39.307] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:32:53.723] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:33:30.807] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:33:37.427] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:33:57.484] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:57:12.958] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:57:19.462] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:205:32)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1237:10)
    at Function.findOne (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1252:13)
    at Function.findById (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1189:15)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:70:7
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:365:14)
[2016-01-26 13:57:46.771] [ERROR] log_file - Error: No default engine was specified and no extension was provided.
    at new View (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\response.js:961:7)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:89:9
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
[2016-01-26 14:00:50.724] [ERROR] log_file - Error: No default engine was specified and no extension was provided.
    at new View (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\response.js:961:7)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:89:9
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
[2016-01-26 14:01:01.851] [ERROR] log_file - Error: No default engine was specified and no extension was provided.
    at new View (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\response.js:961:7)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:89:9
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
[2016-01-26 14:01:09.366] [ERROR] log_file - Error: No default engine was specified and no extension was provided.
    at new View (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\response.js:961:7)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:89:9
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
[2016-01-26 16:21:53.951] [ERROR] log_file - TypeError: Cannot read property '$elemMatch' of undefined
    at Query._castFields (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2555:22)
    at Query._find (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1025:23)
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:156:8
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:18:7
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
[2016-01-26 16:51:51.038] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "123" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-26 16:52:08.726] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: loginFrom_1_loginAccount_1 dup key: { : "qq", : "nathan" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-26 16:53:00.874] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "123" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-26 17:38:10.796] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: loginFrom_1_loginAccount_1 dup key: { : null, : null }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-26 18:08:29.109] [ERROR] log_file - TypeError: console is not a function
    at Object.handle (d:\PROJECTS\xiaobaiju\background\js\common\successHandler.js:16:9)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:31:18
    at model.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\document.js:1717:20)
    at next_ (d:\PROJECTS\xiaobaiju\background\node_modules\hooks-fixed\hooks.js:89:34)
    at fnWrapper (d:\PROJECTS\xiaobaiju\background\node_modules\hooks-fixed\hooks.js:186:18)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:295:13
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:230:5
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:139:7
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:479:5
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:633:5
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
[2016-01-26 18:08:59.011] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1115" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-28 14:55:02.674] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:39:30
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 14:55:21.532] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:39:30
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 14:55:59.370] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:39:32
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 14:56:35.405] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:39:22
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 14:57:32.193] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:40:22
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 14:59:48.721] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:40:22
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 15:06:34.900] [ERROR] log_file - TypeError: Cannot read property '0' of undefined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:40:22
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 15:20:47.728] [ERROR] log_file - TypeError: testIds.length is not a function
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:40:30
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 15:21:29.177] [ERROR] log_file - TypeError: testIds.length is not a function
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:40:30
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-28 15:24:53.136] [ERROR] log_file - SyntaxError: Unexpected identifier
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:42:30
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-29 09:25:46.170] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "112" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 09:31:46.541] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "113" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 09:31:59.477] [ERROR] log_file - MongoError: unknown top level operator: $in
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:1159:67
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 09:44:14.183] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schematype.js:809:18
    at Array.map (native)
    at ObjectId.handleArray (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schematype.js:808:14)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:171:20)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:200:39)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.remove (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1471:10)
    at Function.remove (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1071:13)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:48:10
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
[2016-01-29 09:48:31.051] [ERROR] log_file - Error
    at MongooseError.CastError (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\error\cast.js:18:16)
    at ObjectId.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:134:13)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:173:17)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schematype.js:809:18
    at Array.map (native)
    at ObjectId.handleArray (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schematype.js:808:14)
    at ObjectId.castForQuery (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\schema\objectid.js:171:20)
    at module.exports (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\cast.js:200:39)
    at Query.cast (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:2525:10)
    at Query.remove (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\query.js:1471:10)
    at Function.remove (d:\PROJECTS\xiaobaiju\background\node_modules\mongoose\lib\model.js:1071:13)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:48:10
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
[2016-01-29 10:10:36.789] [ERROR] log_file - ReferenceError: userIds is not defined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:46:14
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-29 10:10:46.844] [ERROR] log_file - ReferenceError: userIds is not defined
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:46:14
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
[2016-01-29 14:13:58.337] [ERROR] log_file - Error: d:\PROJECTS\xiaobaiju\background\views\queryUser.jade:256
    254|                 div(class="fitem")
    255|                     label ID:
  > 256|                     input(id="id_createOrUpdate" type="text" class="easyui-textbox" type="hidden")
    257|                     span(style="color: red;") *
    258|                 div(class="fitem")
    259|                     label 姓名:

Duplicate attribute "type" is not allowed.
    at Tag.Attrs.setAttribute (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\nodes\attrs.js:37:11)
    at Parser.tag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:790:19)
    at Parser.parseTag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:759:17)
    at Parser.parseExpr (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:211:21)
    at Parser.block (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:729:25)
    at Parser.tag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:838:24)
    at Parser.parseTag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:759:17)
    at Parser.parseExpr (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:211:21)
    at Parser.block (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:729:25)
    at Parser.tag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:838:24)
    at Parser.parseTag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:759:17)
    at Parser.parseExpr (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:211:21)
    at Parser.block (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:729:25)
    at Parser.tag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:838:24)
    at Parser.parseTag (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:759:17)
    at Parser.parseExpr (d:\PROJECTS\xiaobaiju\background\node_modules\jade\lib\parser.js:211:21)
[2016-01-29 14:23:04.037] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1113" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 14:26:24.891] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1113" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 14:34:53.172] [ERROR] log_file - ReferenceError: doc is not defined
    at Query.<anonymous> (d:\PROJECTS\xiaobaiju\background\js\routes\user.js:97:31)
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:177:19
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:109:16
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
[2016-01-29 14:37:45.790] [ERROR] log_file - ReferenceError: doc is not defined
    at Query.<anonymous> (d:\PROJECTS\xiaobaiju\background\js\routes\user.js:98:31)
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:177:19
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:109:16
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
[2016-01-29 14:38:43.939] [ERROR] log_file - ReferenceError: doc is not defined
    at Query.<anonymous> (d:\PROJECTS\xiaobaiju\background\js\routes\user.js:98:31)
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:177:19
    at d:\PROJECTS\xiaobaiju\background\node_modules\kareem\index.js:109:16
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
[2016-01-29 17:17:15.766] [ERROR] log_file - Error: Failed to lookup view "searchUser" in views directory "d:\PROJECTS\xiaobaiju\background\views"
    at EventEmitter.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\application.js:579:17)
    at ServerResponse.render (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\response.js:961:7)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:172:9
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\user.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
[2016-01-29 17:36:32.434] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1112" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 17:37:35.397] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "11126" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 17:42:06.419] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1114567" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 17:42:09.134] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1114567" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 17:42:34.694] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1114567" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-29 17:44:38.828] [ERROR] log_file - MongoError: E11000 duplicate key error collection: xiaobaiju.USER index: phone_1 dup key: { : "1116" }
    at Function.MongoError.create (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\utils.js:114:22)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\collection.js:587:23
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:469:9
    at resultHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb\lib\bulk\unordered.js:416:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:772:13
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\topologies\server.js:243:23)
    at Socket.<anonymous> (d:\PROJECTS\xiaobaiju\background\node_modules\mongodb-core\lib\connection\connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[2016-01-30 16:13:24.068] [ERROR] log_file - ReferenceError: user is not defined
    at d:\PROJECTS\xiaobaiju\background\js\routes\admin.js:27:11
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:330:12)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:271:10)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:121:14)
    at d:\PROJECTS\xiaobaiju\background\js\routes\admin.js:19:2
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\layer.js:95:5)
    at d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:277:22
    at param (d:\PROJECTS\xiaobaiju\background\node_modules\express\lib\router\index.js:349:14)
